// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlocklist = "blocklists"

// Blocklist mapped from table <blocklists>
type Blocklist struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	BlockerUserID string    `gorm:"column:blocker_user_id;type:uuid;not null;index:idx_blocklists_blocker_user_id,priority:1" json:"blocker_user_id"`
	BlockedUserID string    `gorm:"column:blocked_user_id;type:uuid;not null;index:idx_blocklists_blocked_user_id,priority:1" json:"blocked_user_id"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	User          User      `json:"user"`
	BlockedUser   User      `gorm:"foreignKey:BlockedUserID;references:ID" json:"blocked_user"`
}

// TableName Blocklist's table name
func (*Blocklist) TableName() string {
	return TableNameBlocklist
}
