// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	ID          int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:カテゴリID" json:"id"`                               // カテゴリID
	Name        string         `gorm:"column:name;type:character varying(50);not null;comment:カテゴリの識別子（英語、小文字、アンダースコア区切り）" json:"name"`             // カテゴリの識別子（英語、小文字、アンダースコア区切り）
	DisplayName string         `gorm:"column:display_name;type:character varying(100);not null;comment:カテゴリの表示名（ユーザーに表示される名前）" json:"display_name"` // カテゴリの表示名（ユーザーに表示される名前）
	Description *string        `gorm:"column:description;type:text;comment:カテゴリの説明" json:"description"`                                             // カテゴリの説明
	IconURL     *string        `gorm:"column:icon_url;type:character varying(255);comment:カテゴリを表すアイコンのURL" json:"icon_url"`                         // カテゴリを表すアイコンのURL
	ColorCode   *string        `gorm:"column:color_code;type:character varying(20);comment:カテゴリの色コード（UI表示用）" json:"color_code"`                     // カテゴリの色コード（UI表示用）
	SortOrder   int32          `gorm:"column:sort_order;type:integer;not null;comment:表示順序" json:"sort_order"`                                      // 表示順序
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now();comment:レコード作成日時" json:"created_at"`   // レコード作成日時
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now();comment:レコード更新日時" json:"updated_at"`   // レコード更新日時
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:論理削除日時（NULLは有効なレコードを示す）" json:"deleted_at"`           // 論理削除日時（NULLは有効なレコードを示す）
	Interests   []Interest     `json:"interests"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
