// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCommunityPostComment = "community_post_comments"

// CommunityPostComment mapped from table <community_post_comments>
type CommunityPostComment struct {
	ID         string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:コメントID" json:"id"`                                                                                 // コメントID
	PostID     *string        `gorm:"column:post_id;type:uuid;index:idx_community_post_comments_post_id,priority:1;comment:投稿ID" json:"post_id"`                                                         // 投稿ID
	UserID     *string        `gorm:"column:user_id;type:uuid;index:idx_community_post_comments_user_id,priority:1;comment:コメント投稿者のユーザーID" json:"user_id"`                                               // コメント投稿者のユーザーID
	ParentID   *string        `gorm:"column:parent_id;type:uuid;index:idx_community_post_comments_parent_id,priority:1;comment:親コメントID（返信の場合）" json:"parent_id"`                                         // 親コメントID（返信の場合）
	Content    string         `gorm:"column:content;type:text;not null;comment:コメント内容" json:"content"`                                                                                                   // コメント内容
	MediaUrls  *string        `gorm:"column:media_urls;type:text[];comment:添付メディアのURL配列" json:"media_urls"`                                                                                              // 添付メディアのURL配列
	LikeCount  int32          `gorm:"column:like_count;type:integer;not null;comment:いいね数（キャッシュ）" json:"like_count"`                                                                                     // いいね数（キャッシュ）
	IsApproved bool           `gorm:"column:is_approved;type:boolean;not null;default:true;comment:承認済みフラグ（モデレーション用）" json:"is_approved"`                                                                // 承認済みフラグ（モデレーション用）
	CreatedAt  time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_community_post_comments_created_at,priority:1;default:now();comment:コメント作成日時" json:"created_at"` // コメント作成日時
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now();comment:コメント更新日時" json:"updated_at"`                                                         // コメント更新日時
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_community_post_comments_deleted_at,priority:1;comment:論理削除日時" json:"deleted_at"`                          // 論理削除日時
}

// TableName CommunityPostComment's table name
func (*CommunityPostComment) TableName() string {
	return TableNameCommunityPostComment
}
