// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCommunityPost = "community_posts"

// CommunityPost mapped from table <community_posts>
type CommunityPost struct {
	ID           string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:投稿ID" json:"id"`                                                                         // 投稿ID
	CommunityID  *string        `gorm:"column:community_id;type:uuid;index:idx_community_posts_community_id,priority:1;comment:コミュニティID" json:"community_id"`                                    // コミュニティID
	UserID       *string        `gorm:"column:user_id;type:uuid;index:idx_community_posts_user_id,priority:1;comment:投稿者のユーザーID" json:"user_id"`                                                 // 投稿者のユーザーID
	Title        *string        `gorm:"column:title;type:character varying(200);comment:投稿タイトル（オプション）" json:"title"`                                                                             // 投稿タイトル（オプション）
	Content      string         `gorm:"column:content;type:text;not null;comment:投稿内容" json:"content"`                                                                                           // 投稿内容
	MediaUrls    *string        `gorm:"column:media_urls;type:text[];comment:添付メディアのURL配列（画像や動画）" json:"media_urls"`                                                                             // 添付メディアのURL配列（画像や動画）
	LikeCount    int32          `gorm:"column:like_count;type:integer;not null;comment:いいね数（キャッシュ）" json:"like_count"`                                                                           // いいね数（キャッシュ）
	CommentCount int32          `gorm:"column:comment_count;type:integer;not null;comment:コメント数（キャッシュ）" json:"comment_count"`                                                                    // コメント数（キャッシュ）
	IsPinned     bool           `gorm:"column:is_pinned;type:boolean;not null;index:idx_community_posts_is_pinned,priority:1;comment:ピン留め投稿フラグ" json:"is_pinned"`                                // ピン留め投稿フラグ
	IsApproved   bool           `gorm:"column:is_approved;type:boolean;not null;default:true;comment:承認済みフラグ（モデレーション用）" json:"is_approved"`                                                      // 承認済みフラグ（モデレーション用）
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_community_posts_created_at,priority:1;default:now();comment:投稿作成日時" json:"created_at"` // 投稿作成日時
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now();comment:投稿更新日時" json:"updated_at"`                                                 // 投稿更新日時
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_community_posts_deleted_at,priority:1;comment:論理削除日時" json:"deleted_at"`                        // 論理削除日時
}

// TableName CommunityPost's table name
func (*CommunityPost) TableName() string {
	return TableNameCommunityPost
}
