// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommunityLike = "community_likes"

// CommunityLike mapped from table <community_likes>
type CommunityLike struct {
	ID        string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID    *string   `gorm:"column:user_id;type:uuid;uniqueIndex:idx_community_likes_comment_user,priority:2;uniqueIndex:idx_community_likes_post_user,priority:2" json:"user_id"`
	PostID    *string   `gorm:"column:post_id;type:uuid;uniqueIndex:idx_community_likes_post_user,priority:1" json:"post_id"`
	CommentID *string   `gorm:"column:comment_id;type:uuid;uniqueIndex:idx_community_likes_comment_user,priority:1" json:"comment_id"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName CommunityLike's table name
func (*CommunityLike) TableName() string {
	return TableNameCommunityLike
}
