// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommunityMember = "community_members"

// CommunityMember mapped from table <community_members>
type CommunityMember struct {
	CommunityID string    `gorm:"column:community_id;type:uuid;primaryKey;comment:コミュニティID" json:"community_id"`                                                                                    // コミュニティID
	UserID      string    `gorm:"column:user_id;type:uuid;primaryKey;index:idx_community_members_user_id,priority:1;comment:ユーザーID" json:"user_id"`                                                 // ユーザーID
	Role        string    `gorm:"column:role;type:character varying(20);not null;index:idx_community_members_role,priority:1;default:member;comment:メンバーの役割（member, moderator, admin）" json:"role"` // メンバーの役割（member, moderator, admin）
	IsApproved  bool      `gorm:"column:is_approved;type:boolean;not null;index:idx_community_members_is_approved,priority:1;comment:承認状態（プライベートコミュニティの場合）" json:"is_approved"`                     // 承認状態（プライベートコミュニティの場合）
	JoinedAt    time.Time `gorm:"column:joined_at;type:timestamp with time zone;not null;default:now();comment:コミュニティ参加日時" json:"joined_at"`                                                        // コミュニティ参加日時
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now();comment:レコード更新日時" json:"updated_at"`                                                        // レコード更新日時
	Community   Community `json:"community"`
	User        User      `json:"user"`
}

// TableName CommunityMember's table name
func (*CommunityMember) TableName() string {
	return TableNameCommunityMember
}
