// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommunityInterest = "community_interests"

// CommunityInterest mapped from table <community_interests>
type CommunityInterest struct {
	CommunityID string    `gorm:"column:community_id;type:uuid;primaryKey" json:"community_id"`
	InterestID  int32     `gorm:"column:interest_id;type:integer;primaryKey" json:"interest_id"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName CommunityInterest's table name
func (*CommunityInterest) TableName() string {
	return TableNameCommunityInterest
}
