// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEducation = "educations"

// Education mapped from table <educations>
type Education struct {
	ID        int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:学歴ID" json:"id"`                               // 学歴ID
	Name      string         `gorm:"column:name;type:character varying(100);not null;comment:学歴名（高卒、専門卒、大卒など）" json:"name"`                     // 学歴名（高卒、専門卒、大卒など）
	SortOrder int32          `gorm:"column:sort_order;type:integer;not null;comment:表示順序" json:"sort_order"`                                    // 表示順序
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now();comment:レコード作成日時" json:"created_at"` // レコード作成日時
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now();comment:レコード更新日時" json:"updated_at"` // レコード更新日時
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:論理削除日時（NULLは有効なレコードを示す）" json:"deleted_at"`         // 論理削除日時（NULLは有効なレコードを示す）
}

// TableName Education's table name
func (*Education) TableName() string {
	return TableNameEducation
}
