// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameInterest = "interests"

// Interest mapped from table <interests>
type Interest struct {
	ID            int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Name          string         `gorm:"column:name;type:character varying(100);not null;index:idx_interests_name,priority:1" json:"name"`
	DisplayName   string         `gorm:"column:display_name;type:character varying(100);not null" json:"display_name"`
	CategoryID    *int32         `gorm:"column:category_id;type:integer;index:idx_interests_category,priority:1" json:"category_id"`
	IconURL       *string        `gorm:"column:icon_url;type:character varying(255)" json:"icon_url"`
	SortOrder     int32          `gorm:"column:sort_order;type:integer;not null" json:"sort_order"`
	CreatedAt     time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Category      Category       `json:"category"`
	UserInterests []UserInterest `json:"user_interests"`
}

// TableName Interest's table name
func (*Interest) TableName() string {
	return TableNameInterest
}
