// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMatch = "matches"

// Match mapped from table <matches>
type Match struct {
	ID          string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:マッチングの一意識別子（UUIDv4）" json:"id"`                                                                 // マッチングの一意識別子（UUIDv4）
	UserId1     string         `gorm:"column:user_id_1;type:uuid;not null;index:idx_matches_user_id_1,priority:1;comment:マッチングしたユーザー1のID" json:"user_id_1"`                                            // マッチングしたユーザー1のID
	UserId2     string         `gorm:"column:user_id_2;type:uuid;not null;index:idx_matches_user_id_2,priority:1;comment:マッチングしたユーザー2のID" json:"user_id_2"`                                            // マッチングしたユーザー2のID
	MatchedAt   time.Time      `gorm:"column:matched_at;type:timestamp with time zone;not null;index:idx_matches_matched_at,priority:1;default:CURRENT_TIMESTAMP;comment:マッチング成立日時" json:"matched_at"` // マッチング成立日時
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:レコード作成日時" json:"created_at"`                                          // レコード作成日時
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:レコード更新日時" json:"updated_at"`                                          // レコード更新日時
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_matches_deleted_at,priority:1;comment:論理削除日時（NULLは有効なレコードを示す）" json:"deleted_at"`                      // 論理削除日時（NULLは有効なレコードを示す）
	User        User           `json:"user"`
	MatchedUser User           `gorm:"foreignKey:MatchedUserID" json:"matched_user"`
}

// TableName Match's table name
func (*Match) TableName() string {
	return TableNameMatch
}
