// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePrefecture = "prefectures"

// Prefecture mapped from table <prefectures>
type Prefecture struct {
	ID        int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:プライマリーキー" json:"id"`                                                   // プライマリーキー
	Code      int16          `gorm:"column:code;type:smallint;not null;comment:都道府県コード（JIS X 0401準拠）" json:"code"`                                                      // 都道府県コード（JIS X 0401準拠）
	Name      string         `gorm:"column:name;type:character varying(4);not null;comment:都道府県名" json:"name"`                                                          // 都道府県名
	NameEn    string         `gorm:"column:name_en;type:character varying(30);not null;comment:都道府県名（英語）" json:"name_en"`                                               // 都道府県名（英語）
	RegionID  int32          `gorm:"column:region_id;type:integer;not null;index:idx_prefectures_region_id,priority:1;comment:地域区分ID" json:"region_id"`                 // 地域区分ID
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:作成日時" json:"created_at"`                 // 作成日時
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:更新日時" json:"updated_at"`                 // 更新日時
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_prefectures_deleted_at,priority:1;comment:削除日時（論理削除用）" json:"deleted_at"` // 削除日時（論理削除用）
	Region    Region         `json:"region"`
	Users     []User         `json:"users"`
}

// TableName Prefecture's table name
func (*Prefecture) TableName() string {
	return TableNamePrefecture
}
