// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserInterest = "user_interests"

// UserInterest mapped from table <user_interests>
type UserInterest struct {
	UserID     string    `gorm:"column:user_id;type:uuid;primaryKey;index:idx_user_interests_user_id,priority:1;comment:ユーザーID" json:"user_id"`              // ユーザーID
	InterestID int32     `gorm:"column:interest_id;type:integer;primaryKey;index:idx_user_interests_interest_id,priority:1;comment:趣味ID" json:"interest_id"` // 趣味ID
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now();comment:関連付け作成日時" json:"created_at"`                  // 関連付け作成日時
	User       User      `json:"user"`
	Interest   Interest  `json:"interest"`
}

// TableName UserInterest's table name
func (*UserInterest) TableName() string {
	return TableNameUserInterest
}
